name: Publish image to docker hub
on:
  [workflow_dispatch]
  
jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t anshuhtwt/demo-app:latest
      - name: publish
        run: |
          docker login -u anshuhtwt ${{ secrets.DOCKERHUB_TOKEN }}
          docker push anshuhtwt/demo-app:latest

