name: push docker image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    # Add additional steps for building and pushing the Docker image
    # ...
